local-address=0.0.0.0
local-port=5300

launch=bind,gmysql
bind-config=/etc/powerdns/bind/named.conf
bind-check-interval=60

primary=yes
secondary=yes
xfr-cycle-interval=60
allow-notify-from=10.20.60.10,10.20.60.14
allow-unsigned-notify=yes

gmysql-host=127.0.0.1
gmysql-port=3306
gmysql-dbname=pdns
gmysql-user=pdns

api=yes
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=127.0.0.0/8,10.0.0.0/8

loglevel=4
version-string=anonymous
default-soa-edit=INCEPTION-INCREMENT
