PDNS_AUTH_API_KEY=op://JesterTek/PowerDNS/PDNS_AUTH_API_KEY
PDNS_RECURSOR_API_KEY=op://JesterTek/PowerDNS/PDNS_RECURSOR_API_KEY
PDNS_DB_ROOT_PASSWORD=op://JesterTek/PowerDNS/PDNS_DB_ROOT_PASSWORD
PDNS_DB_PASSWORD=op://JesterTek/PowerDNS/PDNS_DB_PASSWORD
PDNS_DB_PORT=3306
POWERADMIN_PORT=9191
POWERADMIN_ADMIN_USER=op://JesterTek/PowerDNS/POWERADMIN_ADMIN_USER
POWERADMIN_ADMIN_PASSWORD=op://JesterTek/PowerDNS/POWERADMIN_ADMIN_PASSWORD
