MYSQL_ROOT_PASSWORD=op://JesterTek/NMS Stack/MYSQL_ROOT_PASSWORD
MYSQL_PASSWORD=op://JesterTek/NMS Stack/MYSQL_PASSWORD
GRAYLOG_PASSWORD_SECRET=op://JesterTek/Graylog Stack/GRAYLOG_PASSWORD_SECRET
GRAYLOG_ROOT_PASSWORD_SHA2=op://JesterTek/Graylog Stack/GRAYLOG_ROOT_PASSWORD_SHA2
